### ISSUE TITLE
2.1.0: Build on i386 fails during tests

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#462]
Hi,

When building for Debian, some tests fail on an i386 platform:

```
The following tests FAILED:
    244 - tLSQaips (Failed)
    245 - tLSQFit (Failed)
    272 - tAutoDiff (Failed)
    274 - tClassicalStatistics (Failed)
    279 - tFitToHalfStatistics (Failed)
    282 - tHingesFencesStatistics (Failed)
    289 - tSparseDiff (Failed)
    349 - tLatticeRegion (Failed)
    350 - tLCComplement (Failed)
    351 - tLCConcatenation (Failed)
    352 - tLCDifference (Failed)
    362 - tLCRegion (Failed)
    365 - tLCUnion (Failed)
    420 - tDirectionCoordinate (Failed)
Errors while running CTest
```

Complete log [here](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=i386&ver=2.1.0-1&stamp=1467846711). Similarly [on Ubuntu](https://launchpadlibrarian.net/272418517/buildlog_ubuntu-yakkety-i386.casacore_2.1.0-1_BUILDING.txt.gz). This is also reported as a [Debian bug](https://bugs.debian.org/830250).
The version 2.0.3 run all tests successfull, as seen in [Gijs' repository](https://launchpadlibrarian.net/251858378/buildlog_ubuntu-trusty-i386.casacore_2.0.3-3trusty_BUILDING.txt.gz) (On a different Ubuntu version, however).

**Comment by olebole** [comment]
There a report on this already in #394; however we can see these errors happen only on i386 (x86_64 tests run fine). Also, `--max-parallel=1` is appended to the tests arguments.

**Comment by olebole** [comment]
Most of the failures are due to the 387 FPU that is used on 32-bit x86 and will disappear when compiled with `-msse2 -mfpmath=sse`. With version 2.2RC, there are two failures left: `tRebinLattice` (see #542), and `tTempImage`. The latter creates a Segmentation fault. Here is a stack trace:
```
#0  0xf52801ed in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0xf5280e67 in ?? () from /lib/i386-linux-gnu/libc.so.6
#2  0xf54ac338 in operator delete(void*) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#3  0xf54ac398 in operator delete[](void*) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#4  0xf644839b in casa::TSMCube::~TSMCube (this=0x5677c7e8, __in_chrg=<optimized out>) at ./tables/DataMan/TSMCube.cc:136
#5  0xf644861a in casa::TSMCube::~TSMCube (this=0x5677c7e8, __in_chrg=<optimized out>) at ./tables/DataMan/TSMCube.cc:137
#6  0xf6469336 in casa::TiledStMan::~TiledStMan (this=0x5677eb58, __in_chrg=<optimized out>) at ./tables/DataMan/TiledStMan.cc:85
#7  0xf645b0a3 in casa::TiledCellStMan::~TiledCellStMan (this=0x5677eb58, __in_chrg=<optimized out>) at ./tables/DataMan/TiledCellStMan.cc:70
#8  0xf645b0ca in casa::TiledCellStMan::~TiledCellStMan (this=0x5677eb58, __in_chrg=<optimized out>) at ./tables/DataMan/TiledCellStMan.cc:71
#9  0xf62dd9b3 in casa::ColumnSet::~ColumnSet (this=0x56726c40, __in_chrg=<optimized out>) at ./tables/Tables/ColumnSet.cc:77
#10 0xf6303d01 in casa::PlainTable::closeObject (this=<optimized out>) at ./tables/Tables/PlainTable.cc:312
#11 0xf6303e6b in casa::PlainTable::~PlainTable (this=0x56725bc0, __in_chrg=<optimized out>) at ./tables/Tables/PlainTable.cc:273
#12 0xf6303f2a in casa::PlainTable::~PlainTable (this=0x56725bc0, __in_chrg=<optimized out>) at ./tables/Tables/PlainTable.cc:275
#13 0xf6359274 in casa::Table::~Table (this=0x56726ed4, __in_chrg=<optimized out>) at ./tables/Tables/Table.cc:262
#14 0x5666bda7 in casa::PagedArray<bool>::~PagedArray (this=0x56726ed0, __in_chrg=<optimized out>) at ./casacore/lattices/Lattices/PagedArray.tcc:185
#15 0x5666bf0a in casa::PagedArray<bool>::~PagedArray (this=0x56726ed0, __in_chrg=<optimized out>) at ./casacore/lattices/Lattices/PagedArray.tcc:185
#16 0x5666c501 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5677d2e8) at /usr/include/c++/6/bits/shared_ptr_base.h:150
#17 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x5671a558, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:662
#18 std::__shared_ptr<casa::Lattice<bool>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x5671a554, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:928
#19 std::shared_ptr<casa::Lattice<bool> >::~shared_ptr (this=0x5671a554, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr.h:93
#20 casa::CountedPtr<casa::Lattice<bool> >::~CountedPtr (this=0x5671a554, __in_chrg=<optimized out>) at ./casacore/casa/Utilities/CountedPtr.h:141
#21 casa::TempLatticeImpl<bool>::~TempLatticeImpl (this=0x5671a550, __in_chrg=<optimized out>) at ./casacore/lattices/Lattices/TempLatticeImpl.tcc:74
#22 0x5666c55a in casa::CountedPtr<casa::TempLatticeImpl<bool> >::Deleter<casa::TempLatticeImpl<bool> >::operator() (data=0x5671a550, this=0x5677daf4) at ./casacore/casa/Utilities/CountedPtr.h:95
#23 std::_Sp_counted_deleter<casa::TempLatticeImpl<bool>*, casa::CountedPtr<casa::TempLatticeImpl<bool> >::Deleter<casa::TempLatticeImpl<bool> >, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=0x5677dae8) at /usr/include/c++/6/bits/shared_ptr_base.h:464
#24 0x5665fa91 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5677dae8) at /usr/include/c++/6/bits/shared_ptr_base.h:150
#25 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0xfffbbe74, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:662
#26 std::__shared_ptr<casa::TempLatticeImpl<bool>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0xfffbbe70, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:928
#27 std::shared_ptr<casa::TempLatticeImpl<bool> >::~shared_ptr (this=0xfffbbe70, __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr.h:93
#28 casa::CountedPtr<casa::TempLatticeImpl<bool> >::~CountedPtr (this=0xfffbbe70, __in_chrg=<optimized out>) at ./casacore/casa/Utilities/CountedPtr.h:141
#29 casa::TempLattice<bool>::~TempLattice (this=0xfffbbe6c, __in_chrg=<optimized out>) at ./casacore/lattices/Lattices/TempLattice.tcc:38
#30 0x5665a7a2 in doIt (scratch=...) at ./images/Images/test/tTempImage.cc:81
#31 0x566588aa in main () at ./images/Images/test/tTempImage.cc:241
```
The segmentation fault appears after while returning from the `doIt()` function of `tTempImage.cc`.
