### ISSUE TITLE
update_measures broken

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#854]
When i run it my system i get:
```
Traceback (most recent call last):                   
  File "./update_measures", line 32, in <module>     
    default=detect_domain(),                         
  File "./update_measures", line 13, in detect_domain
    domain = socket.gethostname().split(".")[-2]     
IndexError: list index out of range                  
```
Now you could argue that the machine is wrongly configured since no FQDN is set, but that is the cast with most machines. even if i specify the domain the script crashes since the code still runs.

This works:
```
def detect_domain():                     
    choices = ["atnf", "astron", "nrao"] 
    hostname = socket.gethostname()      
    if '.' in hostname:                  
        domain = hostname.split(".")[-2] 
        if domain in choices:            
            return domain                
    return choices[0]                    
```

But then all options fail again:
```
λ  ./update_measures -l astron data                                                                             
Traceback (most recent call last):                                                                              
  File "./update_measures", line 106, in <module>                                                               
    ftp.cwd(datadirs[OPTS.location])                                                                            
  File "/usr/lib/python2.7/ftplib.py", line 574, in cwd                                                         
    return self.voidcmd(cmd)                                                                                    
  File "/usr/lib/python2.7/ftplib.py", line 256, in voidcmd                                                     
    return self.voidresp()                                                                                      
  File "/usr/lib/python2.7/ftplib.py", line 231, in voidresp                                                    
    resp = self.getresp()                                                                                       
  File "/usr/lib/python2.7/ftplib.py", line 226, in getresp                                                     
    raise error_perm, resp                                                                                      
ftplib.error_perm: 550 Failed to change directory.                                                              
                                                    
λ  ./update_measures -l atnf data                                                                               
Traceback (most recent call last):                                                                              
  File "./update_measures", line 106, in <module>                                                               
    ftp.cwd(datadirs[OPTS.location])                                                                            
  File "/usr/lib/python2.7/ftplib.py", line 574, in cwd                                                         
    return self.voidcmd(cmd)                                                                                    
  File "/usr/lib/python2.7/ftplib.py", line 256, in voidcmd                                                     
    return self.voidresp()                                                                                      
  File "/usr/lib/python2.7/ftplib.py", line 231, in voidresp                                                    
    resp = self.getresp()                                                                                       
  File "/usr/lib/python2.7/ftplib.py", line 226, in getresp                                                     
    raise error_perm, resp                                                                                      
ftplib.error_perm: 550 Can't change directory to pub/software/casacore/measures_data: No such file or directory 
                                                    
λ  ./update_measures -l nrao data                                                                               
Traceback (most recent call last):                                                                              
  File "./update_measures", line 104, in <module>                                                               
    ftp = FTP(dataservers[OPTS.location])   # connect to host, default port                                     
  File "/usr/lib/python2.7/ftplib.py", line 120, in __init__                                                    
    self.connect(host)                                                                                          
  File "/usr/lib/python2.7/ftplib.py", line 135, in connect                                                     
    self.sock = socket.create_connection((self.host, self.port), self.timeout)                                  
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection                                           
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):                                                         
socket.gaierror: [Errno -2] Name or service not known                                                           
```

**Comment by tammojan** [comment]
The update_measures script is likely outdated and should be removed.

**Comment by gijzelaerr** [comment]
the script has been removed.
