### ISSUE TITLE
Question: Table Lock errors

### ISSUE THREAD

**Issue by keflavich** [casacore/casacore#948]
I've been getting `Error (Function not implemented)` errors when trying to load tables for the last two days on a particular CASA system (CV lustre).  I note that there are two related issues from some other places:

https://github.com/ChileanVirtualObservatory/jovial.chivo.cl/issues/13
https://github.com/casacore/casacore/issues/605

neither of which are resolved.  I don't entirely understand where this issue is coming from.  Is there any workaround for these sorts of locking-related issues, or is this a problem linked to the filesystem and/or compile-time options in CASA?

Example traceback:
```
tb.open('W51-E_B3_uid___A001_X1296_X109_continuum_merged_7M_selfcal.ms/HISTORY')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-57-f5d253563713> in <module>
----> 1 tb.open('W51-E_B3_uid___A001_X1296_X109_continuum_merged_7M_selfcal.ms/HISTORY')

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/casatools/table.py in open(self, tablename, lockoptions, nomodify)
    316         doc = {'tablename': tablename, 'lockoptions': lockoptions, 'nomodify': nomodify}
    317         assert _pc.validate(doc,schema), str(_pc.errors)
--> 318         _open_result = self._swigobj.open(_str_ec(_pc.document['tablename']), _dict_ec(_pc.document['lockoptions']), _pc.document['nomodify'])
    319         return _open_result
    320 

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/casatools/__casac__/table.py in open(self, *args, **kwargs)
    444 
    445         """
--> 446         return _table.table_open(self, *args, **kwargs)
    447 
    448 

RuntimeError: Error (Function not implemented) when acquiring lock on /lustre/cv/projects/ALMA_IMF/2017.1.01355.L/W51-E_B3_uid___A001_X1296_X109_continuum_merged_7M_selfcal.ms/HISTORY/table.lock
```

**Comment by gervandiepen** [comment]
It looks as if your Lustre system gives the error 'Function not
implemented' when CTDS tries to acquire a lock.
It's best to open the tables with LoLocking or build casacore with
-DENABLE_TABLELOCKING=OFF. Of course, it means that the tables cannot be
locked, thus should not be accessed concurrently from multiple processes.

**Comment by keflavich** [comment]
How can I open the tables w/LoLocking off?   I can't rebuild casacore, probably not even as a last resort.

**Comment by sjperkins** [comment]
Ger mentioned the following to me in private correspondence:

> Hi Simon,
>
> A single table should be accessed from one thread only; the Table object is not thread-safe. Internally it uses some caching which cannot be shared amongst threads.
However, it is safe to access different tables in different threads.
>
> Reading one table from multiple processes is always safe and does not require locking. But when writing, there can only be a single writer or multiple readers (not both as writing needs an exclusive lock).
>
>Cheers,
>Ger

**Comment by keflavich** [comment]
The problem I reported above was resolved when the locking mechanisms were enabled on the server.  I have a similar problem now, though:
```
In [8]: tb.open('Field12_W51E_test_standard_robust2_20chan.image/')
2019-08-22 13:38:36	INFO		Process 61983: waiting for read-lock on file /Volumes/orange/adamginsburg/ALMA_IMF/w51efield12/field12_tests/Field12_W51E_test_standard_robust2_20chan.image/table.lock
2019-08-22 13:38:36	SEVERE	open::Field12_W51E_test_standard_robust2_20chan.image/	Exception Reported: Error (Operation not supported) when acquiring lock on /Volumes/orange/adamginsburg/ALMA_IMF/w51efield12/field12_tests/Field12_W51E_test_standard_robust2_20chan.image/table.lock
Traceback (most recent call last):
  File "<ipython-input-8-dd9ae021dee4>", line 1, in <module>
    tb.open('Field12_W51E_test_standard_robust2_20chan.image/')
  File "/Users/adam/miniconda3/envs/casa_py36/lib/python3.6/site-packages/casatools/table.py", line 318, in open
    _open_result = self._swigobj.open(_str_ec(_pc.document['tablename']), _dict_ec(_pc.document['lockoptions']), _pc.document['nomodify'])
  File "/Users/adam/miniconda3/envs/casa_py36/lib/python3.6/site-packages/casatools/__casac__/table.py", line 446, in open
    return _table.table_open(self, *args, **kwargs)
RuntimeError: Error (Operation not supported) when acquiring lock on /Volumes/orange/adamginsburg/ALMA_IMF/w51efield12/field12_tests/Field12_W51E_test_standard_robust2_20chan.image/table.lock
```

This is happening on a SAMBA-mounted drive.  Is this a known issue / is there a workaround?
